on:
  push:
    branches:
      - master
      - alpha

name: ðŸš€ Deploy nestjs on push
jobs:
  job1:
    name: ðŸ¸ compute-env-name
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.step1.outputs.env_name }}
    steps:
      - name: get env name
        id: step1
        run: |
          branch_name=${refs: 11}
          if [ "$branch_name" = "master" ]; then
            env_name="production"
          else
            env_name=$branch_name
          fi
          echo "çŽ¯å¢ƒï¼š${env_name}"
          echo "::set-output name=env_name::$env_name"

        env:
          refs: ${{github.ref}}

  nestjs-deploy:
    name: ðŸŽ‰ ã€${{ needs.job1.outputs.env_name }}ã€‘Deploy
    runs-on: ubuntu-latest
    environment: ${{ needs.job1.outputs.env_name }}

    steps:

      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: ðŸ™ˆ Create Env File
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo DATABASE_NAME_1=${{ secrets.DATABASE_NAME_1 }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo USER_PASSWORD_SECRET=${{ secrets.USER_PASSWORD_SECRET }} >> .env

      - name: ðŸ”¨ Build Project
        run: |
          npm ci
          npm run build

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            **/test/**
            package-lock.json
            pnpm-lock.yaml
            .eslintrc.js
            .gitignore
            .prettierrc
            .README.md
            .tsconfig.build.json
            .tsconfig.json
